spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9641c22f93001c4238cd2daee3217d4a
            client-secret: yu16jFNM9w5c0ICHT95mhH0UK6KkuVwk
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image
          naver:
            client-id: _YEkEzAg9plMmAl4Wb_X
            client-secret: yGsVn0VaUr
            redirect-uri:  http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 726872375409-a0bk57l7ieab9f0hcoes34g62fu1u2va.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  profiles:
    includes: oauth
  session:
    store-type:jdbc